DROP TABLE CURRICULUM;
DROP TABLE CURRICULUM_SUBTOPIC;


CREATE TABLE CURRICULUM(
  CURRICULUM_ID INT,
  CURRICULUM_NAME VARCHAR2(50),
  CURRICULUM_VERSION INT,
  CURRICULUM_CREATOR INT,
  CURRICULUM_MODIFIER INT,
  CURRICULUM_DATE_CREATED VARCHAR2(50),
  CURRICULUM_NUMBER_OF_WEEKS INT,
  
  PRIMARY KEY(CURRICULUM_ID),
  FOREIGN KEY(CURRICULUM_CREATOR) REFERENCES USERS(USER_ID),
  FOREIGN KEY (CURRICULUM_MODIFIER) REFERENCES USERS(USER_ID)

);

CREATE TABLE CURRICULUM_SUBTOPIC (
  CURRICULUM_SUBTOPTIC_ID INT,
  CURRICULUM_SUBTOPIC_NAME_ID INT,
  CURRICULUM_SUBTOPIC_CUR_ID INT,
  CURRICULUM_WEEK INT,
  CURRICULUM_DAY INT,
  
  PRIMARY KEY(CURRICULUM_SUBTOPTIC_ID),
  FOREIGN KEY(CURRICULUM_SUBTOPIC_NAME_ID) REFERENCES SUBTOPIC_NAME(SUBTOPIC_NAME_ID),
  FOREIGN KEY(CURRICULUM_SUBTOPIC_CUR_ID)REFERENCES CURRICULUM(CURRICULUM_ID)
  
);
